Documentation:
  Enabled: false

Metrics/AbcSize:
   Max: 20

LineLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'

Metrics/MethodLength:
 Max: 15

Metrics/CyclomaticComplexity:
 Max: 10

Metrics/PerceivedComplexity:
 Max: 10

